language: node_js
node_js:
  - "10" 
branches:
  only:
    - main
script:
  - "yarn run lint"
  - "yarn test"

install:
  - npm install
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm install -g firebase-tools && npm run build; fi'

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then firebase deploy --token $FIREBASE_TOKEN; fi'